### ISSUE TITLE
Discount Renovation Cleveland?

### ISSUE THREAD

**Issue by JasmineNears** [enodekciw/Pisces#1]
Hey, Just realized that when I sign into this theme I do not see this and can not find it anywhere in the editor, but when someone goes to my site they see this. will try to check out the problem for you. wondering where this is coming from: http://www.jumpintosegregation.org/

**Comment by ghost** [comment]
Hey, could you please explain what I should look for? :) Maybe some screenshots?

**Comment by JasmineNears** [comment]
![screen shot 2015-02-02 at 11 25 36 pm](https://cloud.githubusercontent.com/assets/10818001/6014512/317f8cda-ab33-11e4-8f8f-767c100db8f0.png)

**Comment by ghost** [comment]
Oh yes, I do see that 'discount renovation cleveland'.

Could you paste the contents of header.php file? I guess you're using modified version of it?

**Comment by JasmineNears** [comment]
Thanks
